CREATE TABLE `tb_chat` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(20) CHARACTER SET latin1 DEFAULT NULL,
  `message` VARCHAR(3000) CHARACTER SET latin1 DEFAULT NULL,
  `message_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `room_id` VARCHAR(20) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=INNODB DEFAULT CHARSET=utf8